/**
* @name PowerShell html report 2 csv
* @version 1.0 [Abril 4, 2013]
* @author Gustavo Lacoste (gustavo@lacosox.org)
* @fileoverview This script generate a csv files based in a html file generated by PowerShell
* with ConvertTo-html function
* JS Engine tested:
*  - v0.10.4
*/

var fs = require('fs');
var path = require("path");
var cheerio = require("cheerio");
var json2csv = require("json2csv");
var jQuery= require("jQuery");
// la BD unica se genera primero como un json

if(!fs.existsSync(__dirname+'\\in')) fs.mkdir(__dirname+'\\in');
if(!fs.existsSync(__dirname+'\\out')) fs.mkdir(__dirname+'\\out');

// Leyendo todos los html ...
var json = [];
fs.readdirSync(__dirname+'\\in').forEach(function(file) {
	if (file.substr(-5) == '.html'){
		console.log("Leyendo "+file+" ...");
		var htmlSource = fs.readFileSync(path.normalize(__dirname+'\\in\\')+file, "utf16le").replace(/H2/g,'h2');

		var $ = cheerio.load(htmlSource);

		$("body").each(function(i) {

			var categoria=$("h2", this).text().toUpperCase().replace(/ /g,'').replace(/Á/g,'A').replace(/É/g,'E').replace(/Í/g,'I').replace(/Ó/g,'O').replace(/Ú/g,'U').replace(/Ñ/g,'N');

			if(! json[categoria]){
				json[categoria] = [];
			}

			$("table", this).each(function(i) {
				var titulostabla = [];
				$("th", this).each(function(i) {
					titulostabla.push(jQuery.trim($(this).text()));
				});

				var datos = [];
				$("td", this).each(function(i) {
					datos.push($(this).text());
				});

				var id=file.substr(15).replace(".html","").replace(".","");
				var contador=0;

				while(contador<(datos.length/titulostabla.length)){
					var objeto= {};
					var id=file.substr(15).replace(".html","").replace(".","");
					objeto["PK"]=id

					for(var i = 0; i < titulostabla.length; i++){
						objeto[titulostabla[i]] = datos[i+(contador*titulostabla.length)];
					}

					json[categoria].push(objeto);
					contador++;
				}
			});
		});
	}
});

// Generando los ficheros CSV en base al json con los datos.
for (var index in Object.keys(json)) {

	if (index!=0){
		jsoncategoria=json[Object.keys(json)[index]]
		var titulos=Object.keys(jsoncategoria[0])

		// Exportando a CSV único
		json2csv({data: jsoncategoria, fields: titulos}, function(err, csv) {
			if (err) console.log(err);
			var nombre_archivo='out/'+Object.keys(json)[index]
			//console.log(nombre_archivo)
			fs.writeFile(nombre_archivo+'.csv', csv, function(err) {
				if (err) throw err;
				console.log('Archivo '+nombre_archivo+' regenerado');
			});
		});
	}
}